= Node.js + Express.js + Sequelize + SQLite/PostgreSQL + Next.js fullstack static/SSR/ISG Example Realworld App

Got it running on Heroku as of April 2021 at https://cirosantilli-realworld-next.herokuapp.com/

This is a branch of https://github.com/cirosantilli/node-express-sequelize-realworld-example-app rebased on top of the `master` branch of that repository, we show it in a separate GitHub repository just to give it more visibility.

Any information that applies to both repositories will be kept in that README only.

Ideally we would like to have both demos on the same tree as they share all backend code, but Next.js and NPM impose too many restrictions which we don't have the time to work around.

The frontend part of this repository is a fork of https://github.com/reck1ess/next-realworld-example-app/tree/66003772a42bf71c7b2771119121d4c9cf4b07d4 which was SSR only via API, not ISG. We decided to merge it in-tree rather than keep it a separate submodule because the fullstack implementation means that the barrier between front-end and back-end becomes is quite blurred, e.g. "front-end" files under `/pages` also contain functions with direct backend database access without going through the API.

Both Next.js and the backend API run on the same express server via a https://nextjs.org/docs/advanced-features/custom-server[Next.js custom server].

The design goals are similar to https://dev.to/givehug/next-js-apollo-client-and-server-on-a-single-express-app-55l6 except that we are trying to implement the Realworld App :-) GraphQL would be ideal, but its need is greatly diminished by SSR.

Due to ISR/SSR, the entire website should look exactly the same with and without JavaScript for a logged out user.

== Local development with SQLite

....
npm install
npm run dev
....

You can now visit http://localhost:3000[] to view the website. Both API and pages are served from that single server.

== Local optimized frontend

....
npm install
npm run build-dev
npm run start-dev
....

If you make any changes to the code, at least code under `/pages` for sure, you have to rebuild before they take effect in this mode, as Next.js appears to also run server-only code such as `getStaticPaths` from one of the webpack bundles.

Running `next build` is one very important test of the code, as it builds many of the most important pages of the website, and runs checks such as TypeScript type checking.

== Heroku deployment

We are not sure if Next.js ISR can be deployed reliably due to the ephemeral filesystem such as those in Heroku...: https://stackoverflow.com/questions/67684780/how-to-set-where-the-prerendered-html-of-new-pages-generated-at-runtime-is-store

== TODO

=== Personal user data in `/user/settings`

`reck1ess` was using a mixture of SSR and client side redirects.

If you tried to access `/user/settings` directly e.g. by pasting it on the browser, it would redirect you to home even if you were logged in, and the server showed an error message:

....
Error: No router instance found.
You should only use "next/router" inside the client side of your app.
....

We patched to avoid that.

However, we are still currently just using data from the `localStorage`. This is bad because if the user changes details on another device, the data will be stale.

Also this is a very specific case of personal user data, so it doesn't reflect the more general case of data that is not in `localStorage`.

Instead, we should handle `/user/settings` from Next.js server side, notably check JWT token there and 401 if not logged in.

=== Single URL with multiple pages

We don't know how to have multiple pages under a single URL in Next.js nicely. This is needed for tab navigation e.g. under `/` "Your Feed" vs "Global Feed", and for pagination:

* https://stackoverflow.com/questions/62628685/static-pagination-in-nextjs
* https://stackoverflow.com/questions/65471275/material-ui-tabs-with-nextjs

Note however that such functionality also makes it impossible to access those pages without JavaScript, therefore one of the main points of React, which is SEO without the need for JavaScript.

`reck1ess` original implementation works around this by just fetching from the API and rendering, like a regular non-Next React app would.

=== TODO security

Use a markdown sanitizer, the `marked` library `sanitize` option was deprecated.

== Bugs

https://github.com/reck1ess/next-realworld-example-app[] has several UI bugs/missing functionality, some notable ones:

* https://github.com/reck1ess/next-realworld-example-app/issues/22 Your Feed not working

The implementation of `reck1ess/next-realworld-example-app` felt a bit quirky in a few senses:

* usage of `useSWR` even for data that can be already pre-rendered by Next.js such are articles. Presumably this is to give some kind of pool based realtime support? But that is not what other implementations do, and neither should we. We don't want data to update by surprise under a user's feet.
* uses custom https://github.com/emotion-js/emotion[emotion-js] CSS in addition to the global http://demo.productionready.io/main.css[], which is also required.
+
While this is good to illustrate that library, it also means that a lot of reimplementation is needed, and it is hard to be accurate at times.
+
And if it were to use emotion, it should be emotion only, without the global CSS. Instead, that repo uses both, sometimes specifying the same CSS multiple times in two ways.
+
It is also very annoying that they used separated defined components rather than in-tree emotion CSS which can be done as:
+
....
<div css={css`
  font-weight: 300;
`}>
....
+
which leads to a much easier to read DOM tree, and less identifiers flying everywhere.

These are all poinst that we have or would like to address in this fork.
